export default {
    NETWORK_NAME:process.env.REACT_APP_NETWORK_NAME,
    TRACEABILITY_REGISTRY_ADDRESS: process.env.REACT_APP_TRACEABILITY_REGISTRY_ADDRESS,
    NETWORK_URL: process.env.REACT_APP_NETWORK_URL,
    NETWORK_EXPLORER: process.env.REACT_APP_NETWORK_EXPLORER,
    TRACEABILITY_BACKEND: process.env.REACT_APP_TRACEABILITY_BACKEND
}